server:
  port: 9088
spring:
  application:
      name: "gateway-service"
  devtools:
    restart:
      enabled: false
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/


